[package]
name = "torrentrs"
version = "0.1.0"
edition = "2021"

[dependencies]
bendy = "0.3.3"
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["blocking"] }
sha1 = "0.10.6"
urlencoding = "2.1.3"
